const express = require('express');
const { Client, LocalAuth } = require('whatsapp-web.js');
const qrcode = require('qrcode-terminal');

const app = express();
const port = 3000;

app.use(express.json());

// Diccionario de links (ejemplo) basado en el código recibido
const linksDrive = {
    '1':'https://drive.google.com/drive/folders/1rcXb_SCcYbIUJz8HkbGrFu0JMOb99NPi?usp=sharing',
    '2':'https://drive.google.com/drive/folders/1u7vCB2XwHC1uEqxTnUlVaKN4iXM73qvA?usp=sharing',
    '3':'https://drive.google.com/drive/folders/15peddiYI-MJtQRiPflOxbIVCw2FKwIWp?usp=sharing',
    '4':'https://drive.google.com/drive/folders/126ymSPly0e9rbC1RFFETUEBxDj5Ax7mq?usp=sharing',
    '5':'https://drive.google.com/drive/folders/1K8Li5EwHwSSF1PzYDCgpt-bKg5oclen1?usp=sharing',
    '6':'https://drive.google.com/drive/folders/1L75C6T3nHbfsc5lDHeV26V-hTJEQEeQ2?usp=sharing',
    '7':'https://drive.google.com/drive/folders/18ykiyIiCZWzH0mtQQjqSkbUDMD1eLQGy?usp=sharing',
    '8':'https://drive.google.com/drive/folders/14j2ak8yI0inSjef25gYzmxwrjG4IoViC?usp=sharing',
    '9':'https://drive.google.com/drive/folders/1bfFavulSemEY5EqabbTegHwVGGAt05kJ?usp=sharing',
    '10':'https://drive.google.com/drive/folders/1zplszqbQUllof_kN9_Sx36nUyswy0I2B?usp=sharing',
    '11':'https://drive.google.com/drive/folders/1c-n6KUHFOr2Elzdmn-kxGZ0PeVcfO4_r?usp=sharing',
    '12':'https://drive.google.com/drive/folders/1jNZWSyLwQx8Zx7RABjjMtzeIy94PZiVj?usp=sharing',
    '13':'https://drive.google.com/drive/folders/1jf9Uj0t3Li4V_VVkR1N30Qht7BCPE97q?usp=sharing',
    '14':'https://drive.google.com/drive/folders/1wxvjKfoRFH3YE8twL2b2MRd5baPzDg5U?usp=sharing',
    '15':'https://drive.google.com/drive/folders/1wyi2hhm7sQz6kOnSGxvFO7p4k_FO4_M4?usp=sharing',
    '16':'https://drive.google.com/drive/folders/18sVGrkDCM2JwF8r5LhPF2GUuNNPYDdZg?usp=sharing',
    '17':'https://drive.google.com/drive/folders/1_-p9G6fGMWnXI2XkrVAtfzZKpWQYamlF?usp=sharing',
    '18':'https://drive.google.com/drive/folders/19pGR7kRTmskqtvAhFXT6ovwoqbjFnBeq?usp=sharing',
    '19':'https://drive.google.com/drive/folders/1ZULDf7GZnYUKiBixnGHZiwf9C197aNht?usp=sharing',
    '20':'https://drive.google.com/drive/folders/1flPJ4EkosKGRPXQoNGSt3KDrIcTQkfUN?usp=sharing',
    '21':'https://drive.google.com/drive/folders/1M-67wddFAMIT6LNUj2c5VlmCWsWx9G1V?usp=sharing',
    '22':'https://drive.google.com/drive/folders/1r3lEX4I-J2ZIcxErLTbu3utyp3MMk1U_?usp=sharing',
    '23':'https://drive.google.com/drive/folders/18vXgnuT7MeKUIaNMgeikd0qiKUcu5-GB?usp=sharing',
    '24':'https://drive.google.com/drive/folders/1qY4AHR5SypKlpHrz22TXBWv3v3_5zLeK?usp=sharing',
    '25':'https://drive.google.com/drive/folders/111tzBucAVO5ztRPBf4MQlFvtLhZBf7la?usp=sharing',
    '26':'https://drive.google.com/drive/folders/1L1l7DjkORXUIgAzbKzZuZ72dhJKy3mIa?usp=sharing',
    '27':'https://drive.google.com/drive/folders/1F66uKeOay3z8K3579HYGcLSVO3au1Vor?usp=sharing',
    '28':'https://drive.google.com/drive/folders/1QwW1bZQy_ttEL-aZc_vFGMYdjZpQsdTa?usp=sharing',
    '29':'https://drive.google.com/drive/folders/1R4vpWoiC_XX27RPfhrCjSaoaBTQzGz6l?usp=sharing',
    '30':'https://drive.google.com/drive/folders/1htXugrrtUzhysiM0pgePNhO9AVNz95qf?usp=sharing',
    '31':'https://drive.google.com/drive/folders/1fWo51LGjMmWQZts3TOkwX4IwIhcoLSmH?usp=sharing',
    '32':'https://drive.google.com/drive/folders/1TxXPIFLS66G2QS2A45jIs7RMkeSOEviO?usp=sharing',
    '33':'https://drive.google.com/drive/folders/1pxC5rgBS9Un7or3ZfX3iXm7uGbEtMB_g?usp=sharing',
    '34':'https://drive.google.com/drive/folders/1LOIfU94bruPGLLq08ry4-ZLZeRoSeGqz?usp=sharing',
    '35':'https://drive.google.com/drive/folders/13mJUJZSYUXUf4qXbIe2CGghlMieUd0lh?usp=sharing',
    '36':'https://drive.google.com/drive/folders/1tJ38p0BGDgqw8gWgFLd1mCkZ4KG56L9Z?usp=sharing',
    '37':'https://drive.google.com/drive/folders/1-HAO5JRh4StNE-eZw0Dc4Sj6qwcGzetH?usp=sharing',
    '38':'https://drive.google.com/drive/folders/1ldEcAyafJAgneHwN4GyKoKQT5OY8qm35?usp=sharing',
    '39':'https://drive.google.com/drive/folders/189-kgr9eKeFxnStSFpv27JIqOa0Lmn3R?usp=sharing',
    '40':'https://drive.google.com/drive/folders/1G8rtf8ile6Fp7mTvZdZtEV2bJnhRw09m?usp=sharing',
    '41':'https://drive.google.com/drive/folders/1PzKlkZngXduFK2nqiNtiQA_CdjwZOxrC?usp=sharing',
    '42':'https://drive.google.com/drive/folders/1qKJ5xJe0VtkMLdf0stMAuawWcBIgb8OU?usp=sharing',
    '43':'https://drive.google.com/drive/folders/16TUqhZgoNoBMWfPl2ZPKy-9ddkjbNsnn?usp=sharing',
    '44':'https://drive.google.com/drive/folders/1SQzu1xK3USSIDswPezApm7FW40wWyZcu?usp=sharing',
    '45':'https://drive.google.com/drive/folders/1c39ohFgejU4y2f7RzVRmJ0mmqibeSUFF?usp=sharing',
    '46':'https://drive.google.com/drive/folders/1uMOXniiMf5PJIwxu9MkFqdceIpgUlUf0?usp=sharing',
    '47':'https://drive.google.com/drive/folders/1s7ErDUi4Tx8CTv60kKt4_1g_wHtc5RnK?usp=sharing',
    '48':'https://drive.google.com/drive/folders/1DmOfhsJc4N1_K4DNBuAvQnyLFFgBuIpg?usp=sharing',
    '49':'https://drive.google.com/drive/folders/1T2FfzRzVaidW_nwkV2nB2gVXbuooCUQA?usp=sharing',
    '50':'https://drive.google.com/drive/folders/1MGmkDmtYWzDUP3rV_-l23up5DHkBvsWU?usp=sharing',
    '51':'https://drive.google.com/drive/folders/1Zp3-A325n-DIyWN5xUMSbGngkOy6ZBv8?usp=sharing',
    '52':'https://drive.google.com/drive/folders/1KVIYCpu8gyI2GEMsbteWNytOxAfZmYmY?usp=sharing',
    '53':'https://drive.google.com/drive/folders/1jibywE_cakDVgw8uY8qi4SXFaafjTqWe?usp=sharing',
    '54':'https://drive.google.com/drive/folders/1V5U6xYCQye9ZotR6-EY70RMDkYDe86BR?usp=sharing',
    '55':'https://drive.google.com/drive/folders/1CjfADjU_AVfN2YZGTg8Wfs5dCkysseRU?usp=sharing',
    '56':'https://drive.google.com/drive/folders/1hLadEfz6NRGWF_jcLspenVg7x4HSnxRw?usp=sharing',
    '57':'https://drive.google.com/drive/folders/1ms5MLz_n1mZQwJ2xRoqinT69Z3x1aVw2?usp=sharing',
    '58':'https://drive.google.com/drive/folders/1zUyadXXY32N-OTmALZSXt7IF8oWXC0nS?usp=sharing',
    '59':'https://drive.google.com/drive/folders/1sgM8yZiIKP63JqnaVf8TvWxkSS0XXBr9?usp=sharing',
    '60':'https://drive.google.com/drive/folders/1XSTwaLLbSZ0nG-nQQo8VAzT6jeKJUG4a?usp=sharing',
    '61':'https://drive.google.com/drive/folders/1D9-NOJ0deVgfJAid-7j3RrqQUmUieIWd?usp=sharing',
    '62':'https://drive.google.com/drive/folders/1o8Rngb_wJm6lB5fFKDXPDRPT3RcFuxKq?usp=sharing',
    '63':'https://drive.google.com/drive/folders/1RYJ4Y2U8eFath5GKqBdpIo6a-j5M0mnW?usp=sharing',
    '64':'https://drive.google.com/drive/folders/1ExKdUPTX6NTChYWc9mhRfZL-NBIx4uxy?usp=sharing',
    '65':'https://drive.google.com/drive/folders/1oku3f8HbF3RpYhgEGc4QL6SyrkWE5HCf?usp=sharing',
    '66':'https://drive.google.com/drive/folders/1Z80PomzqVW5s8sovvGq53CWcfoetYp4c?usp=sharing',
    '67':'https://drive.google.com/drive/folders/18AZJdq3X5Hqa_g3nDW6QU92cTqC3MkNQ?usp=sharing',
    '68':'https://drive.google.com/drive/folders/15vFW71ziJ1bwECi9xxFyVLa-dXVGc-v6?usp=sharing',
    '69':'https://drive.google.com/drive/folders/1g1gYXSN88V6D3rgXoxt5Bx4VEk_8Tpfx?usp=sharing',
    '70':'https://drive.google.com/drive/folders/1A4GhtKJ0Y8xo4pMMddSDspZjlYbypq-g?usp=sharing',
    '71':'https://drive.google.com/drive/folders/1S2wV9gMbtuJztagqNdb1-05zcem1aYUH?usp=sharing',
    '72':'https://drive.google.com/drive/folders/139uwqRqKQaO0y9AAxocdFAMDD215umxA?usp=sharing',
    '73':'https://drive.google.com/drive/folders/1su0_OXgLF3xrV9Ae7AgJKIGDo0nIwiEx?usp=sharing',
    '74':'https://drive.google.com/drive/folders/1akdZE3Zqjd6DrRGyOlJXuOrrfQt6bQEa?usp=sharing',
    '75':'https://drive.google.com/drive/folders/1mUxBI31t-y2luBmNBCFKTqj_EgdMeiVP?usp=sharing',
    '76':'https://drive.google.com/drive/folders/15yXZeKlbA1dCmxQnLyKE6NCqNb1UQf8A?usp=sharing',
    '77':'https://drive.google.com/drive/folders/1zeE9LqBe3BiIf1gh6nMdXYRuShengNiz?usp=sharing',
    '78':'https://drive.google.com/drive/folders/1jIGiJ_LPeVThjuY5YBy8v9ZnoePtGwTG?usp=sharing',
    '79':'https://drive.google.com/drive/folders/1LdYZFWcsYn6Vbq5Rq91Q1x0LDSlHhUoA?usp=sharing',
    '80':'https://drive.google.com/drive/folders/12rkflBkKnxjQ9LKLzs0uEN1m8IUbNkck?usp=sharing',
    '81':'https://drive.google.com/drive/folders/1RC3zXVoWqPDbHsbfcV4ddNXH_t9GzWvm?usp=sharing',
    '82':'https://drive.google.com/drive/folders/1Sfs9PjvDQ3fEXsr8nBmNJM81Z7kz_YdR?usp=sharing',
    '83':'https://drive.google.com/drive/folders/1bJnbT0HYRQbBpu4wpQYt91gu8kpLDXcH?usp=sharing',
    '84':'https://drive.google.com/drive/folders/1FHtP2pIdu21yBqWZg277T49cqJyE-s0I?usp=sharing',
    '85':'https://drive.google.com/drive/folders/1XeKrYxqdb1vHjW82GbFyYCdAstB9L245?usp=sharing',
    '86':'https://drive.google.com/drive/folders/1ahmnFspPeDl95ZI_SyDCljyQmf58_HPg?usp=sharing',
    '87':'https://drive.google.com/drive/folders/1Hc_wtcs3i8ijtYDOx45w2Hjo54gUvhBC?usp=sharing',
    '88':'https://drive.google.com/drive/folders/1r5Zl2VBzu4ASJ7LArCOc3XVm1nfZPrED?usp=sharing',
    '89':'https://drive.google.com/drive/folders/1MzoiYBISyrQh2M9V-rn1OGUiC-akEJm5?usp=sharing',
    '90':'https://drive.google.com/drive/folders/1e0lp8D-Op-fJcQ756vYn7lwIVShfvXDa?usp=sharing',
    '91':'https://drive.google.com/drive/folders/1sBSRLbd7ImlapWC2S0vJyhjJBwiyb2zc?usp=sharing',
    '92':'https://drive.google.com/drive/folders/1v4YiqfCz4-UdrBdn0dV22clTTx1J3Zdl?usp=sharing',
    '93':'https://drive.google.com/drive/folders/1QK-la0b3cZA-zP0Vt5jB39BreaVcXMPv?usp=sharing',
    '94':'https://drive.google.com/drive/folders/1aKDK-AEmfxI7SFePSc3bPDhZWvy1gh5s?usp=sharing',
    '95':'https://drive.google.com/drive/folders/1FzKYsT-nmLqyd6fepET7OaGEp3go4l07?usp=sharing',
    '96':'https://drive.google.com/drive/folders/1rgBZuRFec7jjr4gHCwDQl-3qRg0Bvl-X?usp=sharing',
    '97':'https://drive.google.com/drive/folders/1nwY58y3PXJ_v9r-Ukdi1tqOgPXJU-vzA?usp=sharing',
    '98':'https://drive.google.com/drive/folders/1qhcp74NES5v0w7l0H-9ri5I1Ex88MqS-?usp=sharing',
    '99':'https://drive.google.com/drive/folders/1BDOnL1R4DmTe5L541QXaqyyAmq-AgpxE?usp=sharing',
    '100':'https://drive.google.com/drive/folders/1q3BcqdjyDJ1pE5Bv78bSq3Q_UYVnXUfg?usp=sharing',
    '101':'https://drive.google.com/drive/folders/1zAtxX9GYO4kFa5KJMF18k5v4rkzxV3WD?usp=sharing',
    '102':'https://drive.google.com/drive/folders/1ZsH9DcN5dX5UrcD2Rqr1s4V9_dTUx9Ky?usp=sharing',
    '103':'https://drive.google.com/drive/folders/1N_TT0ZmcbjJ1JjHP0_NDdkiDOOtNKqtr?usp=sharing',
    '104':'https://drive.google.com/drive/folders/1pVDApmchvkb3dFeSkbpiVEMNk1OOQMpF?usp=sharing',
    '105':'https://drive.google.com/drive/folders/1w-6zPzLitHL3vnr5-_pjO1Vx5PhzaN9N?usp=sharing',
    '106':'https://drive.google.com/drive/folders/1Gw4asZoYn_QTz2362Fe3-cwkg4yH7ONt?usp=sharing',
    '107':'https://drive.google.com/drive/folders/1q77SvJ9-Lfjs690LQ1bYMHFflit-TexD?usp=sharing',
    '108':'https://drive.google.com/drive/folders/14a9LrNirmapqH7Q-yEZQ-mLjce46BgcQ?usp=sharing',
    '109':'https://drive.google.com/drive/folders/1ObkamGptSBonO2Xi1bDSpGprxRSdLDuj?usp=sharing',
    '110':'https://drive.google.com/drive/folders/1Mqf95wn1-etbiilNVGaFAHmQ94o-Qm52?usp=sharing',
    '111':'https://drive.google.com/drive/folders/104FaUsYV9rsEQEowl9rYYoLRJy8uvjO-?usp=sharing',
    '112':'https://drive.google.com/drive/folders/1Jna8JIiKQEBLGhSPazKuXl8Pq_2DS2hx?usp=sharing',
    '113':'https://drive.google.com/drive/folders/1p3V01zfLbBycnaWctaNObLjc4T0gN4ic?usp=sharing',
    '114':'https://drive.google.com/drive/folders/16lU_lkO-bNEjhndyhsp-4T6UTot37O6t?usp=sharing',
    '115':'https://drive.google.com/drive/folders/1f8CeXTyADHss7_CragSnA-7iy2s-tQP3?usp=sharing',
    '116':'https://drive.google.com/drive/folders/1QrkbZmQlBX_QOn_lsUXM0DptOXpnTIo0?usp=sharing',
    '117':'https://drive.google.com/drive/folders/1pC9mM4Rvoj5Y0RcnM5ZuR_nThslIdKGg?usp=sharing',
    '118':'https://drive.google.com/drive/folders/1f5aEOLzsP507vtkbhxTzgZf7t0U5lUp1?usp=sharing',
    '119':'https://drive.google.com/drive/folders/1S0bpU4dwNmPp9w38Xk62IHUwIFKmeAt9?usp=sharing',
    '120':'https://drive.google.com/drive/folders/1PLd3LqMQFxRlT91YoASsjGhZw4wCarae?usp=sharing',
    '121':'https://drive.google.com/drive/folders/1tQa4rAUzoJpmzt34IxpvxeLlzelSRM12?usp=sharing',
    '122':'https://drive.google.com/drive/folders/1F7nS_r65aJ_0rKfz5lMQaD56woxr4X6N?usp=sharing',
    '123':'https://drive.google.com/drive/folders/1msabHX-ScGUZU_R0vjESrikwMPV1lllL?usp=sharing',
    '124':'https://drive.google.com/drive/folders/1EI6XxteHmLx2h_NBreTjBeJ2OMvpfo87?usp=sharing',
    '125':'https://drive.google.com/drive/folders/1JFkSXmXrZokY4m9vR0sidpbIALOEjMLx?usp=sharing',
    '126':'https://drive.google.com/drive/folders/1ruWI1FhNM-NN_m9fsezpLOg2qwjqBAa8?usp=sharing',
    '127':'https://drive.google.com/drive/folders/1e4UscNlL_jVfK1fgHVG1OQ3ro4j09Baw?usp=sharing',
    '128':'https://drive.google.com/drive/folders/1lz02PA9pHW9k4BbZmVwEQdp19lhZ-LLm?usp=sharing',
    '129':'https://drive.google.com/drive/folders/1mvpyHWsMXlRCKJeBklriTMJXA_5_j6R0?usp=sharing',
    '130':'https://drive.google.com/drive/folders/1x5rLZijpYTK0rzWuH7Z17IJGu9l4OPJs?usp=sharing',
    '131':'https://drive.google.com/drive/folders/1uF0UQ7ourUXog-JEsb0yeoO-Xze1OgzV?usp=sharing',
    '132':'https://drive.google.com/drive/folders/18aVeeB_YZ1OhGyBhy1gsg06eJ652hPa1?usp=sharing',
    '133':'https://drive.google.com/drive/folders/1Jid3RHfe9UW0tntlpOfBprlPbAnPPvBu?usp=sharing',
    '134':'https://drive.google.com/drive/folders/1Ym49Etanc31b1SiJIJV443XtI3sgtS_d?usp=sharing',
    '135':'https://drive.google.com/drive/folders/1pxAPtW7652svYtuDMwlzyjSloZdNskVC?usp=sharing',
    '136':'https://drive.google.com/drive/folders/1s4oKgo9JN4_yvDReDPDX614RF5_RvzQ-?usp=sharing',
    '137':'https://drive.google.com/drive/folders/1AHmWBMOllGOXiSKMnwZg1XwUHbHUMvOB?usp=sharing',
    '138':'https://drive.google.com/drive/folders/1-bT_lv-poPX3vtkEnAFeLs5wLu9DO996?usp=sharing',
    '139':'https://drive.google.com/drive/folders/1OBlwTb94kh5NtrxoaKNHMS-eC0v6wZL9?usp=sharing',
    '140':'https://drive.google.com/drive/folders/1TyNxqgmefHZiCvmmiWjp1ybCR3lcDIHo?usp=sharing',
    '141':'https://drive.google.com/drive/folders/1Fxmg0AZKe5FVrDPQVAN8ifHh9fKkynbI?usp=sharing',
    '142':'https://drive.google.com/drive/folders/10ogFyFt3IEl3DgLehbTtsiEGkoWc5Uzn?usp=sharing',
    '143':'https://drive.google.com/drive/folders/1YPovOfj0gsuEHzmQ1kbozO5Di574RJBS?usp=sharing',
    '144':'https://drive.google.com/drive/folders/1UgtmXyPaZak3vFpJkOga-1sfm0UrnAlS?usp=sharing',
    '145':'https://drive.google.com/drive/folders/1Qdz66MckfZCEoRhu58pNarkZp07aa6wH?usp=sharing',
    '146':'https://drive.google.com/drive/folders/1GBGmq1RIwJ0FxkKn6V7K99xAKKAjdQPm?usp=sharing',
    '147':'https://drive.google.com/drive/folders/1dVJsbydfclW27_tmWvV1zwS-jGWPoBIS?usp=sharing',
    '148':'https://drive.google.com/drive/folders/1aQoSp3faHrCgr6LOgZNUTIH_ZWdxDLcp?usp=sharing',
    '149':'https://drive.google.com/drive/folders/1NPDZqC_-OmpCmH6fVjHuDvFqXkwYjzeM?usp=sharing',
    '150':'https://drive.google.com/drive/folders/1W0ahNg0EYDhIA7ER93Gjtuk5xoqOc_v8?usp=sharing',
    '151':'https://drive.google.com/drive/folders/1DbbXsNu2CYGjkgrEp_BfRN4fh6gfAfoI?usp=sharing',
    '152':'https://drive.google.com/drive/folders/1Jb8xOVpUzJeHOZ6ZCL1sPzXRlXL6BOcE?usp=sharing',
    '153':'https://drive.google.com/drive/folders/1pkLEN-trnf31l_U2OEgdxdS8SEZvrapx?usp=sharing',
    '154':'https://drive.google.com/drive/folders/182r_N8HjqkXHt4lT3eALNBGbaRdDEmlW?usp=sharing',
    '155':'https://drive.google.com/drive/folders/1gP6sZ3_W23CHowK1Lta7itR7ObhnawwB?usp=sharing',
    '156':'https://drive.google.com/drive/folders/1fqG2Fhb4deJQ75FSY0W17SVHpRvkncMp?usp=sharing',
    '157':'https://drive.google.com/drive/folders/12wT_JxQdv1NjBgmnuW_gRC1ijqHA4AmR?usp=sharing',
    '158':'https://drive.google.com/drive/folders/1JphFyVsXII64M8eriHvvvn19lSFTtS2v?usp=sharing',
    '159':'https://drive.google.com/drive/folders/1wxagMoItnglm4gN0z50lhixbDOVx1sHJ?usp=sharing',
    '160':'https://drive.google.com/drive/folders/1JO1TrqAHx8MA1PwpG70cNqFtmh_QdnVi?usp=sharing',
    '161':'https://drive.google.com/drive/folders/1n4gKEgxLBwTaaSHOhIuPj4w5bhZCQ5SN?usp=sharing',
    '162':'https://drive.google.com/drive/folders/1x9uhoDLedykt4mAWj4DxkJ2mFB1bCrQA?usp=sharing',
    '163':'https://drive.google.com/drive/folders/1Pb6MDNZ0TvdX2ZstgSZDqcs8BWsPeKGF?usp=sharing',
    '164':'https://drive.google.com/drive/folders/1QHQQxRU1TXD93TWg7mrJ-UtT6LOYmazO?usp=sharing',
    '165':'https://drive.google.com/drive/folders/1ioWRqBqDPxw8P7cBD-6qTrlBJ1N_nHm0?usp=sharing',
    '166':'https://drive.google.com/drive/folders/1vztboMfl2mWSLCfTsf9NDrMIPP1ZbAc8?usp=sharing',
    '167':'https://drive.google.com/drive/folders/1uGFV6JA-MntGuxMbfRPPOSH-8O_VTRkf?usp=sharing',
    '168':'https://drive.google.com/drive/folders/1MKGs034gZT-bpWoXgLhvvKsm19sIl9Mz?usp=sharing',
    '169':'https://drive.google.com/drive/folders/1mKuQ4ZwrTyREJRSMtl_7MzVcYnb6FdlS?usp=sharing',
    '170':'https://drive.google.com/drive/folders/1mP_1Gab7-Zo4NK67cnCM3LU2m7muFmTG?usp=sharing',
    '171':'https://drive.google.com/drive/folders/1IF4Rfw8M8lsijTrGko2M4voGvJ4g67qV?usp=sharing',
    '172':'https://drive.google.com/drive/folders/10PIZDmUncF0YbLqOD4vKm9trkU3aOegQ?usp=sharing',
    '173':'https://drive.google.com/drive/folders/1Jil7MxOzc4HE22V1SrPxc__n7yQ9Ige3?usp=sharing',
    '174':'https://drive.google.com/drive/folders/1Dp5lFSZcuJ49jLiULJ_RB4QUUZKpnUDc?usp=sharing',
    '175':'https://drive.google.com/drive/folders/17OQYPWD4XKEqG4hp2SXTDXSS8AmFbDvq?usp=sharing',
    '176':'https://drive.google.com/drive/folders/1ifzVk5xbPPssZQMx7jFVs0J-NgpbTPqc?usp=sharing',
    '177':'https://drive.google.com/drive/folders/1ckAAKwwam8GWW5DKU55RxBlM7Pl2AZeg?usp=sharing',
    '178':'https://drive.google.com/drive/folders/12kQLsY6K0S9idX4UWabShqCDiTWOy21E?usp=sharing',
    '179':'https://drive.google.com/drive/folders/1u9YLjeRCaH9P7xZlAkH1-FQlInRkvtAL?usp=sharing',
    '180':'https://drive.google.com/drive/folders/1-AV_4vsMdq5mNEw2q11UgA7YOvGeD15I?usp=sharing',
    '181':'https://drive.google.com/drive/folders/11hSFvQyenPrzGh49pfT_sYar2z8jifHh?usp=sharing',
    '182':'https://drive.google.com/drive/folders/1LcMkPvVL_iIp6Aty2T4Tkbeko_mdjctB?usp=sharing',
    '183':'https://drive.google.com/drive/folders/1kC_HHCgkvDWt6CBTaEC-n4YMxUIV50LE?usp=sharing',
    '184':'https://drive.google.com/drive/folders/1V32rqEqnmrHmNzm_Wpt7EDq42gj30Fru?usp=sharing',
    '185':'https://drive.google.com/drive/folders/1VGQujQc09hXknFZuCwngsIOvybK45C5-?usp=sharing',
    '186':'https://drive.google.com/drive/folders/1pRu3l5nY_V8mBfEa-Ue99VvFvuFAdWDR?usp=sharing',
    '187':'https://drive.google.com/drive/folders/1Agz9ZJ3Cr4Ik2LeCO-nYw5H9URuAcGkR?usp=sharing',
    '188':'https://drive.google.com/drive/folders/1qZvVaXWL8isy0uJqiZLbJosFXR2zje9u?usp=sharing',
    '189':'https://drive.google.com/drive/folders/1qmAm96U1mc8f-rfFhaRKv2x5PCmEyiMm?usp=sharing',
    '190':'https://drive.google.com/drive/folders/1qftpZ6yZCHd43E-NHHllLOR9gr6PtSdi?usp=sharing',
    '191':'https://drive.google.com/drive/folders/1qbbLU2DOEw-LwyHIob4SxvbIf5DYxUQt?usp=sharing',
    '192':'https://drive.google.com/drive/folders/1r3H7U7tPfy1wKbYicOqEPOEbXNHVINoB?usp=sharing',
    '193':'https://drive.google.com/drive/folders/1qxHwT0bM7wUXGGsJDjK4DtdAL94l7K1G?usp=sharing',
    '194':'https://drive.google.com/drive/folders/1qxFVnqBqOJb3TymYrJtAopY0oYko9i0B?usp=sharing',
    '195':'https://drive.google.com/drive/folders/1qwvpGz3vsiC1J9knnb5pH3o8kmcoae2R?usp=sharing',
    '196':'https://drive.google.com/drive/folders/1qvizCLO8pPqjZb71YmZfDxtQSy8wnS64?usp=sharing',
    '197':'https://drive.google.com/drive/folders/1qrFgFfT-WZCKptDt-MYH_IRIvSuvNXe8?usp=sharing',
    '198':'https://drive.google.com/drive/folders/1qnMI8KriyU4TM2WBfQr80OmUxy_NNaKp?usp=sharing',
    '199':'https://drive.google.com/drive/folders/1r7sFDFcY47EDHtw1Vxxqo6bZk_3SIYrv?usp=sharing',
    '200':'https://drive.google.com/drive/folders/1rBtfhXLcD-OIaPEtxQ3MVBFf_j0ADnCv?usp=sharing',
    '201':'https://drive.google.com/drive/folders/1r9nbYa6VggkfW8aBuPI_nn33JZwNX7-j?usp=sharing',
    '202':'https://drive.google.com/drive/folders/1r99mBOJOsYYQ0qieSlY_sVxsm8vQFkou?usp=sharing',
    '203':'https://drive.google.com/drive/folders/1rFybWxWRzo5PbEffiR95XMqsL3OKgv_S?usp=sharing',
    '204':'https://drive.google.com/drive/folders/1rCU6ZnQX3yx4fNcgEjcgrABC55kSrCAq?usp=sharing',
    '205':'https://drive.google.com/drive/folders/1rVrO_mxZrxGxbgG7KMMrMOSdZ0385skB?usp=sharing',
    '206':'https://drive.google.com/drive/folders/1rTqK6abEQMJ-bBQNExjAQ_tkoUSyEs8H?usp=sharing',
    '207':'https://drive.google.com/drive/folders/1rMsVRlW7DUk12K6ED3SxqyOrKcT9V-bQ?usp=sharing',
    '208':'https://drive.google.com/drive/folders/1rGW_09xKUz0QtfVAJTT_cnNJwi_xcmV2?usp=sharing',
    '209':'https://drive.google.com/drive/folders/1rbSg_gQ7cS_GSNF55wJLmpF-a5SxPgsJ?usp=sharing',
    '210':'https://drive.google.com/drive/folders/1r_66VpIaPZEw10uneCY0KPgfXLAm6w3M?usp=sharing',
    '211':'https://drive.google.com/drive/folders/1rXyizAgI2RbxHt3HXj36YZbssd8jsjHF?usp=sharing',
    '212':'https://drive.google.com/drive/folders/1rkM3rTknKj6Fm_1yn5AoqJ38mi4wV7MM?usp=sharing',
    '213':'https://drive.google.com/drive/folders/1rdS2wo3XqLSPFKlEmsvxitBOiUrQpHEp?usp=sharing',
    '214':'https://drive.google.com/drive/folders/1rpP-Vak4f4ewlkbl16qx0p3hgMDdyW-Q?usp=sharing',
    '215':'https://drive.google.com/drive/folders/1rlhXKqlPXBxlonF7Y0A0BRO7yLXIP_ck?usp=sharing',
    '216':'https://drive.google.com/drive/folders/1ruqVMaKxwOaXDONryaNVtOVP3uLvjRxa?usp=sharing',
    '217':'https://drive.google.com/drive/folders/1sBGNzYw3hsqAEEdiHbpNxdvvJnY34T2U?usp=sharing',
    '218':'https://drive.google.com/drive/folders/1s6-JwXtoqtHLr9c6ao1andy2yot55YRQ?usp=sharing',
    '219':'https://drive.google.com/drive/folders/1sC4RsL-Q9cVRzgrIQAPB68Py8uVmGBe8?usp=sharing',
    '220':'https://drive.google.com/drive/folders/1sRNVsYHER48JYrtz4LZhknqVwvkqoOZ1?usp=sharing',
    '221':'https://drive.google.com/drive/folders/1sHF2mzYLT5dpRkhrVn08sQWCpgBVm5z3?usp=sharing',
    '222':'https://drive.google.com/drive/folders/1sRajChtZsp3Uyp4TG4O3YR7zkYCn5u8r?usp=sharing',
    '223':'https://drive.google.com/drive/folders/1sX4w25WnIV80nSocl9xbgE5mpInw0chE?usp=sharing',
    '224':'https://drive.google.com/drive/folders/1sVYg-3q1pkhaEusVFL1GqXfHJewP4LTz?usp=sharing',
    '225':'https://drive.google.com/drive/folders/1sTPloJFkuxxgtHwSnwdydHjVrq2xXcpw?usp=sharing',
    '226':'https://drive.google.com/drive/folders/1sozJIaadza09dxRPnNJ666LbOWyHeBAH?usp=sharing',
    '227':'https://drive.google.com/drive/folders/1sjSunzhqOjJBrzfIddUZMc7LuM-KjKEq?usp=sharing',
    '228':'https://drive.google.com/drive/folders/1sihLAwQ0GPb_HwuFoxDA3b3cnCWwIIPf?usp=sharing',
    '229':'https://drive.google.com/drive/folders/1suUv-3097s_m1uUOOlxl9jjXdf5sd7yG?usp=sharing',
    '230':'https://drive.google.com/drive/folders/1stzW2myVHFU5KNHdHsgGy8vapUiXkLlq?usp=sharing',
    '231':'https://drive.google.com/drive/folders/1sqhhrl0t7sZZfBhtRkhhc7rbrJZzA9HM?usp=sharing',
    '232':'https://drive.google.com/drive/folders/1tGzz5SP2KlImn7KYUCQQuwXRh5TteBFZ?usp=sharing',
    '233':'https://drive.google.com/drive/folders/1tE20digz_N3OV2pGEeZpJqmDP8UOHlT7?usp=sharing',
    '234':'https://drive.google.com/drive/folders/1tAv27-RcpQWu6AInklXBga-3gP_9iHVJ?usp=sharing',
    '235':'https://drive.google.com/drive/folders/1tARTroV5RqPSFlddYWIr0l8nmGX1DYwq?usp=sharing',
    '236':'https://drive.google.com/drive/folders/1szwCoh05C0Wc4S5DJqaFEzRDgyh43Fdx?usp=sharing',
    '237':'https://drive.google.com/drive/folders/1tQIWlYcQRje5R5S8T11m615P2Y4yjuHT?usp=sharing',
    '238':'https://drive.google.com/drive/folders/1tNjg8KihKg4uqAVJJfFQ6xVPVh45aRoY?usp=sharing',
    '239':'https://drive.google.com/drive/folders/1tMOknDjMm7eBlq3_YWAddQo5HjGNwoqt?usp=sharing',
    '240':'https://drive.google.com/drive/folders/1tHMxYK6MXJdzF1k2OFe5hDW5xL_1Q0y1?usp=sharing',
    '241':'https://drive.google.com/drive/folders/1tc_RaMRrde2jLW_xGT3t58IsmJcW7s7M?usp=sharing',
    '242':'https://drive.google.com/drive/folders/1tZAhns1xiY9cS5Xrb5th15g901vlXfGe?usp=sharing',
    '243':'https://drive.google.com/drive/folders/1tRcQcPD94lanRRkKFgvBVW90kzkna9dH?usp=sharing',
    '244':'https://drive.google.com/drive/folders/1tR9dYDJ_oZaYgy6-i7JPBryeEOBN0iWX?usp=sharing',
    '245':'https://drive.google.com/drive/folders/1u8exu3Tpl4aWLuVpnwsKSxyJmeJNGpGG?usp=sharing',
    '246':'https://drive.google.com/drive/folders/1u79aSFnmk7w_dmdtIUIPQtt9YKmiYT_5?usp=sharing',
    '247':'https://drive.google.com/drive/folders/1tlUlwb8zFPX4EWFaafC70vIS4NDY-C9a?usp=sharing',
    '248':'https://drive.google.com/drive/folders/1tjqOWxg1pzZPuQw9fC5mTiBuiZ2tfaFW?usp=sharing',
    '249':'https://drive.google.com/drive/folders/1th8-rtVGHUikchClOqSyC3tQBeoWV_tF?usp=sharing',
    '250':'https://drive.google.com/drive/folders/1uF24RIQfytCoJRenmz3PZeTAdaLNymET?usp=sharing',
    '251':'https://drive.google.com/drive/folders/1uDGMeqGADhGhMhHu2UfdTi1wfj62ywJO?usp=sharing',
    '252':'https://drive.google.com/drive/folders/1uKMEvF-fcbboC2Xv5HEvvI5PPW4NnRZi?usp=sharing',
    '253':'https://drive.google.com/drive/folders/1um82RUBQ3PzegkpAbHCD29q3PLkGf16I?usp=sharing',
    '254':'https://drive.google.com/drive/folders/1ukkXLflfjp5_n45vjIZW-eqi8SbVyJ4j?usp=sharing',
    '255':'https://drive.google.com/drive/folders/1ugeA_Dbm9vwYSgJSDAds2LGy71tLFkCK?usp=sharing',
    '256':'https://drive.google.com/drive/folders/1uXHe7iC7omg1vUuJQ7aniPeMdb0lb64d?usp=sharing',
    '257':'https://drive.google.com/drive/folders/1uN8bU4g-ujm4haOj-nBfl349cwokvKKG?usp=sharing',
    '258':'https://drive.google.com/drive/folders/1uMd017uKrFQbYxjR2ox_VC0OQWI8Avcp?usp=sharing',
    '259':'https://drive.google.com/drive/folders/1v1VvbywvlAGJXCJjUv-wvypLidbwB1Kd?usp=sharing',
    '260':'https://drive.google.com/drive/folders/1v0r-9J4N-qISOPtRZBXdu_lh7A_guvg_?usp=sharing',
    '261':'https://drive.google.com/drive/folders/1uv0DhIVZaaqgMzpB5ReDNdP2ECCgTl3f?usp=sharing',
    '262':'https://drive.google.com/drive/folders/1un1Put39WrAHffXMNWLJ0ZwqzTu7nTfv?usp=sharing',
    '263':'https://drive.google.com/drive/folders/1v77t-u_i8--ABjGPHUqmnX-7VDP9_1S1?usp=sharing',
    '264':'https://drive.google.com/drive/folders/1v3YAMBsyCMG_KCcjYRbMLtmQP_c9jS_a?usp=sharing',
    '265':'https://drive.google.com/drive/folders/1v2I_aUcy5iC0JvpyL5tz5Cx9Jh7wg4oz?usp=sharing',
    '266':'https://drive.google.com/drive/folders/1v7CUaG37Zqub5DSLkoUXfa5JgMdDHLJw?usp=sharing',
    '267':'https://drive.google.com/drive/folders/1vCgUQi_uKb7LRIBztD0VSsM4SU16Cl0V?usp=sharing',
    '268':'https://drive.google.com/drive/folders/1v85oCTL7w8UxyNZo0c_utTStxwo6bg1a?usp=sharing',
    '269':'https://drive.google.com/drive/folders/1vad1jlWez4VuhvzSGVhugHG-a7PlARgx?usp=sharing',
    '270':'https://drive.google.com/drive/folders/1vZUfeSLfPBvX70KzjbxKmf-jPfRbdHu_?usp=sharing',
    '271':'https://drive.google.com/drive/folders/1vM2AtpYe3Ms-AjnQqlg-LWImzd-ItWwi?usp=sharing',
    '272':'https://drive.google.com/drive/folders/1vKeE_gFRuHScoaAhG-0rlCXGnoAl_XOL?usp=sharing',
    '273':'https://drive.google.com/drive/folders/1vCldKa0vez0jiUO5m53_S3vWsnuZ6Gee?usp=sharing',
    '274':'https://drive.google.com/drive/folders/1vpY8FchqPsdm3ixpUQQ0wEZtIHV7BYBB?usp=sharing',
    '275':'https://drive.google.com/drive/folders/1vjBR38C2Bb6Qk0bNwQtU68SfUFspS0gO?usp=sharing',
    '276':'https://drive.google.com/drive/folders/1varokI5MSmEP6yOvoYClXMD89G1F1x8w?usp=sharing',
    '277':'https://drive.google.com/drive/folders/1vtyqtugHetE2ekXatS2RUF12PXBUnxTh?usp=sharing',
    '278':'https://drive.google.com/drive/folders/1w9VGuOedFdrsmz3NY39XOh0cLSCVxJy5?usp=sharing',
    '279':'https://drive.google.com/drive/folders/1w4RT0d1UiRgric17Cm1EZ6WxmZKi3oGe?usp=sharing',
    '280':'https://drive.google.com/drive/folders/1vzcwt9Z3xesYkGywPXjwaqOcIHWfjdeJ?usp=sharing',
    '281':'https://drive.google.com/drive/folders/1vyutvQ2eIaDs3d39YK9tyMMhrVrDzdho?usp=sharing',
    '282':'https://drive.google.com/drive/folders/1wGAgXp31QSocbiaXL6X0Cl4cE67ffVG5?usp=sharing',
    '283':'https://drive.google.com/drive/folders/1wEGvDDtW08cm1D3EsRKpZp_m9ad_qTZg?usp=sharing',
    '284':'https://drive.google.com/drive/folders/1wCg_IHJGuHgWt-0gj_OO37l6RHm6f5fy?usp=sharing',
    '285':'https://drive.google.com/drive/folders/1wAg35uhf5k7pSjehZvjD7yRgwU_r-5o7?usp=sharing',
    '286':'https://drive.google.com/drive/folders/1whlbVxjFX5Gtti30MkC_r9oHWgX1o-3D?usp=sharing',
    '287':'https://drive.google.com/drive/folders/1wg_V2cRnmnbAO7OCNuvRLvfsFZnXP8du?usp=sharing',
    '288':'https://drive.google.com/drive/folders/1wcPmjsXDDVhinXfMUYUMv0TGHElKW4lg?usp=sharing',
    '289':'https://drive.google.com/drive/folders/1wUusxrXkuC0Yd4lns9f2loW2jUzbkj96?usp=sharing',
    '290':'https://drive.google.com/drive/folders/1wUjXWJrerkFsLH8qrjQLPI-pJfgpMsJk?usp=sharing',
    '291':'https://drive.google.com/drive/folders/1wIOGysl86jhLWmzjzWzZC90_ehCAJt-w?usp=sharing',
    '292':'https://drive.google.com/drive/folders/1wxuaHaDAcqYmiM7R2tt94z2akIRS8OCg?usp=sharing',
    '293':'https://drive.google.com/drive/folders/1wx6-H5wQJzk2AUzO13UOtLQU-DMhb6Ho?usp=sharing',
    '294':'https://drive.google.com/drive/folders/1wwiE39a2OWJkpzKKGyXUrVyjHSdbZh-7?usp=sharing',
    '295':'https://drive.google.com/drive/folders/1wu3fB6_woQJDQ1TdeO1GUbocy21MkUyw?usp=sharing',
    '296':'https://drive.google.com/drive/folders/1xBP6pIWkUKNendAKP_UW1E2U0TzCCGq4?usp=sharing',
    '297':'https://drive.google.com/drive/folders/1xAVB7x6fDGrZ0XMAQ1fLqkRiou_iu8eU?usp=sharing',
    '298':'https://drive.google.com/drive/folders/1x5OppZF-Od5y5qKX43Janm98U7LhO9-U?usp=sharing',
    '299':'https://drive.google.com/drive/folders/1x3AiOnxgbzKl-qUpXW_gO0Pq7nReWt0U?usp=sharing',
    '300':'https://drive.google.com/drive/folders/1xhK49fNDmn3xDYfsl7TeF7oG6dlCBy-e?usp=sharing'
};

// Inicialización del cliente de WhatsApp con persistencia de sesión
const client = new Client({
    authStrategy: new LocalAuth(),
    puppeteer: { headless: true } // En producción, podrías cambiar a true
});

// Muestra el QR en consola para escanearlo
client.on('qr', (qr) => {
    console.log('QR recibido, escanéalo con tu teléfono:');
    qrcode.generate(qr, { small: true });
});

// Indica que el cliente está listo para enviar mensajes
client.on('ready', () => {
    console.log('El cliente de WhatsApp está listo!');
});

// Endpoint para recibir la data desde tu Google Form o script externo
app.post('/send-wsp', async (req, res) => {
    const { number, code } = req.body;

    if (!number || !code) {
        return res.status(400).json({ error: 'El número y el código son requeridos' });
    }

    // Buscar el link de fotos basado en el código recibido
    const linkPhoto = linksDrive[code] || 'No hay link disponible';

    // Personaliza el mensaje según tus necesidades
    const message = `Hola,\n\nGracias por participar en nuestro evento.\n\nAquí tienes el link de tu foto: ${linkPhoto}\n\nSaludos,\nPROMPERU`;

    try {
        // El identificador de WhatsApp se forma agregando '@c.us'
        const chatId = `${number}@c.us`;

        // Envía el mensaje utilizando el cliente de WhatsApp
        await client.sendMessage(chatId, message);
        res.status(200).json({ success: true, message: 'Mensaje enviado correctamente' });
    } catch (error) {
        console.error('Error al enviar mensaje:', error.message);
        res.status(500).json({ success: false, error: 'Error enviando mensaje', details: error.message });
    }
});

// Inicia el servidor Express
app.listen(port, () => {
    console.log(`Servidor corriendo en http://localhost:${port}`);
});

// Inicializa el cliente de WhatsApp
client.initialize();